# Config.yaml
# created at 2022年7月27日 by Shang
#
# 注意:
# 冒号后面一定要有空格
# 缩进要用空格
# 选项不区分大小写

# sourceDir:
# 这里指定包含日志文件的源文件夹, 程序会自动遍历该目录下的所有日志文件, 包括子目录, 注意格式:
#  - "这里输入一个目录"
#  - "可以再添加一个目录"
#  - “”
# 举例:
#  - C:\Users\shang\GolandProjects\logAnalyzer\logs
#  - D:\logs
sourceDir:
  - ./logs

# outputDir: "这里指定输出文件目录, default表示输出到源日志文件所在目录"
outputDir: default

# marshalIndent: true/false 表示json文件是否格式化缩进, 格式化可以让json文件结构更清晰, 但解析速度会变慢, 并且文件也会变大
marshalIndent: false

# verbose: true/false 是否输出详细信息
verbose: true

# format: string/numeric 输出json数据类型: string表示输出的数据全部是字符串格式, numeric表示输出的数据是数字类型. 使用string类型会使解析速度加快
format: string

# multiThreads: true/false 表示是否启用多线程来提高解析速度
multiThreads: true

# timing: true/false 是否计算解析用时
timing: true
